### ISSUE TITLE
Authenticate/login

### ISSUE THREAD

**Issue by juliakimchung** [Ludicrous-Ducks/bangazon_AngularJS#10]
Feature Description:

The non-user/customer should be able to view the product detail but not able to create products or buy products
This view will have non user/customer to register/login before being able to create or buy products
This view will contain a form to register and login

Story

As a visitor to the Bangazon mobile site:
Given I want to create or buy a product
When I perform a gesture on the cart affordance in the navigation area
Then I should be presented with form of register or login
And once I register and login, I should be able to go to any page I want on the Bangazon mobile site.

Scenarios

Given that I'm not a user of Bangazon
And I'm viewing the product list site 
When I click on the add to my order button or create product button,
I am directed to login
Given that I am not authenticated user
I'm presented a form to register first. 
Then I can log in with the username and password.

Given that I'm a user of Bangazon
And I'm Logged Out
When I click on the My Cart affordance in the Navigation Pane
Then I want to be routed to the Login affordance

Context

What should the feature do?
All visitors to the website should be able to see details about their order.

When and where should the feature appear?
The feature appears when a visitor to the site activates the My Cart affordance

Requirements

Potential Impact on Code or Other Features
The order details code may impact other code:
that opens a new order if no active order exists
that adds payment type to order
that closes an order
Correlating Issue if Applicable

#1

**Comment by Onodric** [comment]
Transferred to AngularTake2
