### ISSUE TITLE
creating $http.post method for products in the factory

### ISSUE THREAD

**Issue by juliakimchung** [Ludicrous-Ducks/bangazon_AngularJS#11]
## Expected Behavior
This post method will save the product that's been created by the user

## Actual Behavior
When customer create a product, saveProduct promise will be called form a product Ctrl to save

## Steps to Reproduce Behavior 
Create a saveProduct promise in the factory

## Module Suspected / Relevant Files 
ProductCtrl.js, ProductFactory.js

## Related Issues 
-

**Comment by Onodric** [comment]
Not MVP
