### ISSUE TITLE
product_type_factory.js

### ISSUE THREAD

**Issue by juliakimchung** [Ludicrous-Ducks/bangazon_AngularJS#13]
## Expected Behavior
The user can create the product type and save 

## Actual Behavior
Can save the product type using the post method in the factory by $http.post.

## Steps to Reproduce Behavior 
create SaveProductType promise in the product_type_factory.js

## Module Suspected / Relevant Files 
ProductTypeCtrl.js

## Related Issues 
-

**Comment by Onodric** [comment]
Not MVP
