### ISSUE TITLE
Create product

### ISSUE THREAD

**Issue by juliakimchung** [Ludicrous-Ducks/bangazon_AngularJS#5]
##Feature Description:

The user/customer should be able to view the product list to choose the product, the customer should be shown the last 20 products added to the platform under the product type.
The user/customer can create products to sell using the 'create product form'.
The user/customer can choose the product to buy from the product list.
The view should contain an Add to Order button to buy a product.

##Story

As a visitor to the Bangazon website
In order to buy a product
I want to see a page that lists 20 products added to the platform under the product type
I want to see a page that show a form to choose the product and to add to my order
In order to sell a product
I want to see a page that shows a form to create a product 

##Scenarios

Given that I'm a user of Bangazon
When I click on a product link on the Product list page
Then I want the selected product to be displayed on its own a Product Details page
And I want a button to buy the product

When I click on the button "Sell a product from the nav bar" 
Then I want to see a form to create a product 
To be listed on the most recent product added on the product list

##Context

What should the feature do?
All visitors to the website should be able to see details about products.
All user/customer should be able to create a product to sell

When and where should the feature appear?
The feature appears when a visitor to the website clicks a link to a product to view the detail and buy
The create feature should appear when a user/customer clicks "sell a product" on the nav bar.

##Requirements

Potential Impact on Code or Other Features
The product details code may impact other code:
code that adds a product to an order
Correlating Issue if Applicable

#2

**Comment by Onodric** [comment]
Not MVP.
