### ISSUE TITLE
Reconciling Database

### ISSUE THREAD

**Issue by pinkston4** [Ludicrous-Ducks/bangazon_AngularJS#9]
## Expected Behavior
- There should be a joint database that the Api, django project, and angular project all share. 

## Actual Behavior
- Currently the api and django projects have separate databases with their own models.

## Module Suspected / Relevant Files 
- All fields will need to mirror each in all models. Then naming convention will need to be refactored and made uniform across all modules of both the API project, and Django project.

## Known Discrepancies

# PaymentType
- In the django project the model `PaymentType` in the Api the model is `PaymentMethod`
- Fields in `PaymentType`: customer, payment_type, account_number, ccv, expiration_date
- Fields in `PaymentMethod`: created(date created), name(type), account_number, customer

# Order
- in both projects the model is `Order`
- the fields for the django project are: customer, completed, payment_type, product(many to many)
- the fields for the API project are: active, created, payment method, customer
- # IMPORTANT the django project used a many to many field to store products on the order, the API used a join table where the order's pk is used as the fk 

# ProductType
- in the Django project the model is `ProductType` in the API it is `ProductCategory`
- the django project has two fields, the created(date) and the label(name of type)
- the API only has one field: the name of product category

# Product
- in both projects the model is Product
- the django project fields: created(date), name, price, description, quantity, product_type, customer
- the API  fields: created(date) name, price, quantity_available, description, product_category, and the seller(user who posted product)

# ALSO NOTE THE API DOES NOT HAVE A CUSTOMER MODEL

**Comment by Onodric** [comment]
Closed in another project. Completed
